/*
 * ODK ROBOT Plugin
 * Copyright © 2026 Damien Goutte-Gattat
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package org.incenp.obofoundry.odk;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.apache.commons.cli.CommandLine;
import org.incenp.obofoundry.odk.fixreport.IFixableError;
import org.incenp.obofoundry.odk.fixreport.LowercaseDefinitionError;
import org.incenp.obofoundry.odk.fixreport.MissingObsoleteLabelError;
import org.obolibrary.robot.CommandState;

/**
 * A command to attempt to automatically fix the trivial issues revealed by the
 * <code>report</code> command.
 * <p>
 * In the context of this command, “trivial” issues are issues that should not
 * require manual intervention on each affected term. For now, this means the
 * “obsolete missing label” issue and the “lowercase definition” issue.
 * <p>
 * This requires the report to have been generated with
 * <code>--labels false</code>, so that entities affected by an issue are
 * reported with their ID rather than their label.
 */
public class FixRobotReportCommand extends BasePlugin {

    public FixRobotReportCommand() {
        super("fix-robot-report", "fix trivial errors revealed by the report command",
                "robot fix-robot-report --input <FILE> --robot-report <FILE> --output <FILE>");

        options.addOption(null, "robot-report", true, "the file generated by the report command");
    }

    @Override
    public void performOperation(CommandState state, CommandLine line) throws Exception {
        if ( !line.hasOption("robot-report") ) {
            throw new Exception("Missing required option --robot-report");
        }

        for ( IFixableError error : parseRobotReport(line.getOptionValue("robot-report")) ) {
            error.fixError(state.getOntology());
        }
    }

    private Collection<IFixableError> parseRobotReport(String file) throws IOException {
        List<IFixableError> errors = new ArrayList<>();
        BufferedReader reader = new BufferedReader(new FileReader(file));

        try {
            String line = null;
            while ( (line = reader.readLine()) != null ) {
                String[] items = line.split("\t");
                if ( items.length < 5 ) {
                    continue;
                }
                if ( items[1].equals("lowercase_definition") ) {
                    errors.add(new LowercaseDefinitionError(ioHelper.createIRI(items[2]), items[4]));
                } else if ( items[1].equals("missing_obsolete_label") ) {
                    errors.add(new MissingObsoleteLabelError(ioHelper.createIRI(items[2]), items[4]));
                }
            }
        } finally {
            reader.close();
        }

        return errors;
    }
}
